import bpy
import json
import os

# Configuration: Path to the manifest generated by Unity VibeBridge
MANIFEST_PATH = "/home/bamn/UnityVibeBridge/blender_reconstruction.json"
# Configuration: Folder where textures were collected
TEXTURES_DIR = "/home/bamn/UnityVibeBridge/Export_Blender"

def setup_vibe_materials():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        return

    with open(MANIFEST_PATH, 'r') as f:
        data = json.load(f)

    shade_info = data.get("shade_info", {}).get("list", [])
    
    for info in shade_info:
        mesh_name = info.get("mesh")
        slot_idx = info.get("slot")
        mat_name = info.get("material")
        textures = info.get("textures", [])

        # Find object in Blender
        obj = bpy.data.objects.get(mesh_name)
        if not obj:
            print(f"Warning: Mesh '{mesh_name}' not found in scene.")
            continue

        if slot_idx >= len(obj.material_slots):
            print(f"Warning: Mesh '{mesh_name}' has no material slot {slot_idx}.")
            continue

        # Get or create material
        mat = bpy.data.materials.get(mat_name)
        if not mat:
            mat = bpy.data.materials.new(name=mat_name)
            mat.use_nodes = True
        
        obj.material_slots[slot_idx].material = mat
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links
        
        # Simple Principled BSDF setup
        bsdf = nodes.get("Principled BSDF")
        if not bsdf:
            bsdf = nodes.new('ShaderNodeBsdfPrincipled')

        # Map textures
        for tex in textures:
            key = tex.get("key")
            unity_path = tex.get("path")
            filename = os.path.basename(unity_path)
            local_path = os.path.join(TEXTURES_DIR, filename)

            if not os.path.exists(local_path):
                # Try finding it in the same dir as manifest if not in Export_Blender
                local_path = os.path.join(os.path.dirname(MANIFEST_PATH), filename)

            if os.path.exists(local_path):
                tex_node = nodes.new('ShaderNodeTexImage')
                tex_node.label = key
                try:
                    img = bpy.data.images.load(local_path)
                    tex_node.image = img
                    
                    # Basic mapping logic
                    if key in ["_MainTex", "_BaseColor", "_Albedo"]:
                        links.new(tex_node.outputs['Color'], bsdf.inputs['Base Color'])
                    elif key in ["_BumpMap", "_NormalMap"]:
                        # Setup Normal Map node
                        norm_node = nodes.new('ShaderNodeNormalMap')
                        links.new(tex_node.outputs['Color'], norm_node.inputs['Color'])
                        links.new(norm_node.outputs['Normal'], bsdf.inputs['Normal'])
                        img.colorspace_settings.name = 'Non-Color'
                    elif key in ["_EmissionMap"]:
                        links.new(tex_node.outputs['Color'], bsdf.inputs['Emission Color'])
                except Exception as e:
                    print(f"Error loading image {local_path}: {e}")
            else:
                print(f"Warning: Texture file not found: {local_path}")

    print("Blender Material Setup Complete.")

if __name__ == "__main__":
    setup_vibe_materials()
